### ISSUE TITLE
Solve the cors error in the Front-End project 

### ISSUE THREAD

**Issue by rayane-barbosa** [scooby-doo-cade-voce/frontend#75]
When the page is uploaded the cors errors show up.

Investigate what is happening and fix it: 

![image](https://github.com/scooby-doo-cade-voce/frontend/assets/82448039/12a2cc32-b304-4599-b475-cfb112017faf)

**Comment by ylyra** [comment]
Não é erro no frontend, só falta de configuração de cors no backend
